# Site settings
title: Dragon Tutorials
email: kent.lee@hpe.com
description: >- # this means to ignore newlines until "baseurl:"
  The purpose of this site is to provide tutorials and how-tos related to Dragon.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: kentdlee

# Theme settings
theme: minima

# Minima specific settings (if applicable)
minima:
  date_format: "%b %-d, %Y" # Example: Oct 27, 2024
  # skin: dark # Uncomment to enable dark mode if supported by the theme

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  # Add other plugins as needed